language: python
python:
  - "3.6"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install django -q
# command to run tests
script: 
 - coverage run --source='.' ./manage.py test