language: python
python:
  - "3.2"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
# command to run tests
script: 
  - python manage.py migrate
  - python manage.py test
env:
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.5